### ISSUE TITLE
Fix handling of GEOS exceptions 

### ISSUE THREAD

**Issue by chrispahm** [chrispahm/geos-wasm#13]
Despite experimenting with some of the tips outlined in https://emscripten.org/docs/porting/Debugging.html?highlight=exception, I haven't been able to receive actual GEOS exceptions with the corresponding error messages in the WASM build.

This makes debugging difficult, since the `table index out of bounds` stack trace solely contains info about which function threw the exception, but not really what the underlying issue may be.

**Comment by sanak** [comment]
@chrispahm If you meant not WASM exception handling, but GEOS CAPI exception handling, I guess that GEOS CAPI only provides notice/error message handlers.
- [C API Programming | GEOS](https://libgeos.org/usage/c_api/)

https://github.com/libgeos/geos/blob/main/capi/geos_c.h.in#L97-L117
```cpp
/**
* Callback function for passing GEOS error messages to parent process.
*
* Set the \ref GEOSMessageHandler function for error and notice messages using
* \ref initGEOS or \ref initGEOS_r.
*
* \param fmt the message format template
*/
typedef void (*GEOSMessageHandler)(const char *fmt, ...);

/**
* A GEOS message handler function.
*
* \param message the message contents
* \param userdata the user data pointer that was passed to GEOS when
* registering this message handler.
*
* \see GEOSContext_setErrorMessageHandler
* \see GEOSContext_setNoticeMessageHandler
*/
typedef void (*GEOSMessageHandler_r)(const char *message, void *userdata);
```

The problem is that 1st major handler requires C variant args (`, ...`), but it seems not to be supported in emscripten, so I used 2nd minor version (which is also used in Shapely).
https://github.com/search?q=repo%3Ashapely%2Fshapely%20GEOSContext_setErrorMessageHandler_r&type=code

**Comment by chrispahm** [comment]
Ok thanks for digging into this!

It's unfortunate that we can't get the varargs version of the `GEOSMessageHandler` to work! There was an [issue](https://github.com/emscripten-core/emscripten/issues/5563) and a [closed PR](https://github.com/emscripten-core/emscripten/pull/5684) in the Emscripten repo, but it seems they have been abandoned...

Anyways, I just added a test for the 2nd approach, so that works as expected: https://github.com/chrispahm/geos-wasm/blob/main/test/tests/message_handling.spec.mjs. It would have probably been better to use the reentrant version of the functions in all of the test, since its a) helping with debugging errors and b) seems to be the preferred approach for using GEOS anyways?

**Comment by sanak** [comment]
> It's unfortunate that we can't get the varargs version of the GEOSMessageHandler to work! There was an https://github.com/emscripten-core/emscripten/issues/5563 and a https://github.com/emscripten-core/emscripten/pull/5684 in the Emscripten repo, but it seems they have been abandoned...

Thanks for emscripten issue/PR links!
(I heard about it from somewhere, but I forgot where it is...
It may be possible with using something memory-stack related functions, but full low-level assembly knowledge may be necessary...)

> Anyways, I just added a test for the 2nd approach, so that works as expected: https://github.com/chrispahm/geos-wasm/blob/main/test/tests/message_handling.spec.mjs.

Okay, thanks!
I confirmed that all tests passed. 😄

> It would have probably been better to use the reentrant version of the functions in all of the test, since its a) helping with debugging errors and b) seems to be the preferred approach for using GEOS anyways?

Well, Shapely seems to use above approach. (There seems to be none-reentrant CAPI call.)

And in that case, always adding `_r` at the last of function name is kind of bothering work for API users, so very thin wrapping context handler may be comfortable for the API users (like Shapely 😅).

Here is my idea:
- Prepare context handler property in `allCFunctions.mjs` - `geos` object.
  ```diff
   export const geos = {
  +  handle: null,
     Module: {
  ```
- Save context handler when calling `GEOS_init_r` internally.
  ```diff
  -  geos.GEOS_init_r = Module.cwrap('GEOS_init_r', 'number', [])
  +  geos.GEOS_init = function () {
  +    if (geos.handle) {
  +      console.log('GEOS already initialized');
  +      return
  +    }
  +    geos.handle = Module.ccall('GEOS_init_r', null, [null], [])
  +  }
  ```
- Wrap `_r` reentrant version functions with calling `ccall` instead of `cwrap`.
  ```diff
  -  geos.GEOSFree_r = Module.cwrap('GEOSFree_r', null, ['number', 'number'])
  +  geos.GEOSFree = function (obj) {
  +    Module.ccall('GEOSFree_r', null, ['number', 'number'], [geos.handler, obj])
  +  }
  ```
- Clean up context handler when calling `GEOS_finish_r` internally.
  ```diff
  -  geos.GEOS_finish_r = Module.cwrap('GEOS_finish_r', null, ['number'])
  +  geos.GEOS_finish = function () {
  +    Module.ccall('GEOS_finish_r', null, ['number'], [geos.handler])
  +    geos.handler = null
  +  }
  ```

With above thin wrapping context handler, exposing functions amount will be about a half, because none-reentrant version functions are not necessary. 😊

**Comment by sanak** [comment]
Oh, sure.
It is nice approach to support both users. 😄

> and finally create the non-reentrant functions with a simple generic function
> ```mjs
> Object.keys(geos).forEach(property => {
>   if (typeof geos[property] === 'function' && property.endsWith('_r') {
>     const nonReFunctionName = property.slice(0, -2)
>     geos[nonReFunctionName] = (...args) => geos[property](geos._ctx, ...args)
>   }
> })

And above is kind of magic for me. 🪄😊
